const Phrases = {
  a: [
    'accept not accepting',
    'accept acceptance',
    'audit belief',
    'acknowledgement the unacknowledged',
    'achieve to achieve less',
    'asynchronous',
    'ability is not agility',
    'advise aversion',
    'about last night...',
    'adult conversations',
    'audit the truth of auditing',
    'ascend greatness mountain',
    'answering the call',
    'aspire to inspire aspirations',
    'anger leads to hate',
  ],

  b: [
    'being ok with ok',
    'best self',
    'bring it',
    'being wonderful',
    'beating expectations',
    'behave like adults',
    'bring snacks',
    'believe in belief',
    'bacon is gross',
    'back to basics',
    'belief is believing',
    'brilliance is brilliant',
    'be brilliant',
    'better call saul',
    'breaking bad was awesome',
    'brilliance breeds ideas',
  ],

  c: [
    'cauterize the wounds',
    'caring',
    'care',
    'care to dare',
    'courage',
    'courageous courage',
    'crippling the competition',
    'competitive',
    'cool your jets',
    'cop to the consequences',
    'consequences',
    'conspiracies',
    'convoluted pricing',
    'capture the flag',
    'collaboration',
    'calibrate the collaborators',
    'calibrate profits',
    'calibrate expectations',
    'calibrate courage',
    'collaborate with calibrated care',
    'calibrate care',
    'critical thinking',
    'calibrate critical resources',
    'constant calibration',
    'calibrate your constants',
    'constrain the contraints',
    'conceive conceptions',
    'concepts calibrate competition',
  ],

  d: [
    'dangerous passion berries',
    'dial those phones',
    'dedication to the dedicated',
    'dangerous dedication',
    'drive for driving',
    'drive to dedicated passion',
    'drive thru fear',
    "don't dabble",
    'drive to places',
    'drooling at meetings will be punished',
    'dedication at the expense of health',
    'delivering excellence',
    'delivering deliverables',
    'daring is not carebearing',
    'dare to be daring',
    'dark thoughts',
  ],

  e: [
    'energetic energy',
    'energy does not define taste',
    'engage in engaging stuff',
    'enormous water dinosaurs',
    'engaging the real',
    'easy is good',
    'empty pockets means an empty heart',
    'enemy of my frenemy',
    'ever thought about eating a cloud?',
    'evacuate your vowels',
    'exacting revenge for wealth',
    'excitement is exciting',
    'exuberance smells',
    'extreme power is powerful',
    'extreme group projects',
    'extreme edification',
  ],

  f: [
    'finite resources',
    'future-ability',
    'face the face you fear',
    'faces make faces',
    'fear fears the fearful',
    'fear being filled with fear',
    'fearful optimism',
    'fake numbers',
    'fake news bruh',
    'fake media stole it',
    'fake fake fake',
    'fake it until you make it',
    'frappes are delightful',
    'fraudulent is felonious',
    'free snake friday',
    'free snack friday',
    'fear leads to anger',
    'feel your feels',
    'fuel your feels',
    'feels lead to feeling',
    'friction only leads to slowdown',
    'finger guns close sales',
    'freedom to freely be free',
  ],

  g: [
    'grab awesome by the awesome gland',
    'go get it',
    'gravitate towards greatness',
    'greatness never paid for freedom',
    'gaps are traps',
    'gauge the room',
    'growing can be good',
    'growing can be bad',
    'growing is knowing',
    'get after it',
    'granular greed',
    'giggles are contagious',
    'gratification is gratifying',
    'greatness at the expense of good',
    'good is the enemy of great',
    'great is the enemy of awesome',
    'gather resources',
  ],

  h: [
    'help others be helpful',
    'hardcore profits',
    'hate leads to suffering',
    'healthy greed',
    'healthy health',
    'health is not wealth',
    'hit your targets',
    'home is not work',
    'honor is usually overrated',
    'honor is also honour',
    'honor and health',
    'honor thy boss',
    'how is your mom?',
  ],

  i: [
    'ignore trends',
    'institute goals',
    'ingratiation will be tolerated',
    'ingest greatness',
    'incite a riot of profit',
    'institute ideas',
    'ideas are idyllic',
    'ideas drive innovation',
    'ignore fear',
    'ignore the imitators',
    'imitate whenever you can',
    'imitation is success',
    'in-fighting is not encouraged',
    'insignificance is not allowed',
    'imagine images',
    'imagine dragons',
    'imagination can be imaginative',
  ],

  j: [
    'jumble ideas',
    'jigsaw the norm',
    'join together',
    'jump at opportunity',
    'jam your day with money',
    'jumble convention',
    'jump for great ideas',
    'jump into success',
    'jingle all the way',
  ],

  k: [
    'kick down doors',
    'karate chop opposition',
    'kingpins are winners',
    'kindness never got a bonus',
    'kick start briliance',
    'keep moving fast',
    'keep it simple',
    'keep your courage',
    'keep your keys',
    'keys unlock things',
    'keys of imagination unlock dreams',
    'know the unknowns',
    'knowledge is knowing you can know',
    'know what you know',
    'know that knowing is courage',
    'know when to know',
    'keep knowing',
  ],

  l: [
    'love yourself',
    'light a fire of greatness',
    'list your goals',
    'learn from your enemy',
    'leave stupid at the door',
    'legs take you places',
    'learn to learn',
    'live to learn',
    'love to live',
    'love to learn',
    'lean in',
    'lose nothing',
    'lose yourself in greed',
    'lava is failure',
    'let it go, let it go',
  ],

  m: [
    'marginalize everything',
    'make things better',
    'move at the speed of movement',
    'make moves',
    'minimize thought',
    'minimize loss',
    'minimize loss of thought',
    'minimize forfeiture',
    'minimize minimizing',
    'maximize thought',
    'maximize loss of loss',
    'maximize forfeitures of forfeits',
    'maximize profits',
    'manuever change',
    'manuever profit obsticles',
  ],

  n: [
    'normalize normality',
    'normal is not normal',
    'needs are like needy wants',
    'navigate change',
    'navigate profits',
    'navigate greed',
    'navigate collaboration',
    'not all heroes wear capes',
    'never give up profits',
    'night time is the right time',
    'navigate courage',
    'navigate sales',
    'navigate energy',
    'navigate normal',
    'notches are for belts',
  ],

  o: [
    'oppose change',
    'oppose failure',
    'operate at high efficiency',
    'oppose losing profits',
    'oppose the poseable',
    'oppose the posers',
    'operate operationally',
    'overestimate estimates',
    'overreach the unreachable',
    'overcompensate and underwhelm',
    'over promise and under deliver',
    'overt courage',
    'overt profitability',
    'over the top',
    'open door policy',
    'openness and honesty',
    'open to more profits',
    'open to closed ideas',
    'open to change',
    'open to courage',
    'open to opportunity',
  ],

  p: [
    'prepare, prepare, prepare',
    'postpone losses',
    'presuppose suppositions',
    'propose courage',
    'prepay parking',
    'prevent forfeitures',
    'prevent failure',
    'pregame the big game',
    'pass the buck',
    'prefill the forms',
    'postpone collaboration',
    'preemptive co-operation',
    'preliminary prepository prepositions',
    'pay it forward',
    'positive change',
    'preemptive profits',
    'prequalify success',
  ],

  q: [
    'quiz success',
    'quell the haters',
    'quick judgements',
    'quick responsiveness',
    'quick success',
    'quiz the norm',
    'quick profits',
    'quake with success',
    'quake with courage',
    'quake with collaboration',
    'quake II was awesome',
  ],

  r: [
    'responsive design',
    'reasonable is nothing',
    'react reactively',
    'revise your success',
    'revisit visitation schedules',
    'remove doubt',
    'remove fear',
    'remove complexity',
    'remove the norm',
    'react with courage',
    'react with ideas',
    'react with profitable rage',
    'reason with collaboration',
    'reason opposed to reaction',
    'reaction opposes to reason',
    'remove reaction',
    'remove reason',
    'relive the good times',
    'relive the bad times',
    'reconstitute sales',
    'reconstitute courage',
    'reconstitute opposition',
  ],

  s: [
    'supply demand',
    'source resources',
    'supplant suppositions',
    'subvert the norm',
    'subject matter experts',
    'sever the bad',
    'sever tied ties',
    'snakes are nope ropes',
    'severus snape',
    'suppose you stop whining',
    'standing is erect sitting',
    'sequence the sequential',
    'standby for success',
    'sell the sellable things',
    'sales first, courage whenever',
    'sales first, success pre-first',
    'sales first, profits first',
    'standardize amazingness',
    'supercalifragilisticexpialidocious',
    'sucking sucks',
    'sweat less sweat and more blood',
    'sweet lawd',
    'swing for the fences',
    'secrets are fun',
    'secrecy builds morale',
    'sweet kicks',
    'sometimes lie to win',
    'supply work place dogs',
  ],

  t: [
    'total control',
    'take control',
    'turn a profit',
    'turn to success',
    'turn to courage',
    'turn to ideas',
    'take time to win',
    'take competitors by force',
    'twist the truth',
    'truth and time management',
    'truth and ideas',
    'truth and success',
    'truth and collaboration',
    'truth and courage',
    'turn up the heat',
    'take a dive',
    'try change',
    'try success',
    'try profits',
    'try winning',
    'try collaboration',
    'try and try again',
    'twist words to win',
    'total domination',
    'tweak a nudge',
    'try being cheap',
    'tremble when scared',
    'tame the untameable',
    'twister is not office approved',
  ],

  u: [
    'underachieve',
    'underwhelm',
    'use good judgement',
    'unilateral decision making',
    'unimaginative ideas',
    'understanding',
    'understanding ideas',
    'understanding demand',
    'understanding sales',
    'understanding decisions',
    'undo your mistakes',
    'undo your failures',
    'undo your fear',
    'undo your doubt',
    'ubiquitous ubiquity',
  ],

  v: [
    'vulcanize your drive',
    'vacate fear',
    'vote for courage',
    'validate profits',
    'validate sales',
    'validate self',
    'validate success',
    'visible ideas',
    'visible imagination',
    'vroom vroom the business',
    'velociraptor the weak',
  ],

  w: [
    'watch greatness',
    'wish for change',
    'wish for courage',
    'water down ideas',
    'waffle on ideas',
    'wag the dog',
    'wind up the business',
    'waiver on the complex',
    'witness imagination',
    'witness change',
    'witness struggle',
    'wise up',
    'worry for nothing',
    "where's waldo?",
  ],

  x: [
    'x-amine ideas',
    'x-ceed goals',
    'x-ceed the normal',
    'x-treme profits',
    'x-ert dominance',
    'x-ert compliance',
    'x-ceed greatness',
    'x is a stupid letter',
  ],

  y: [
    'you are the engine',
    'you make business run',
    'you are the idea',
    'y axis to 100%',
    'you are courage',
    'you are success',
    'you are profit',
    'yesterday is not today',
    'yesterday was yesterday',
    "yesterday's idea is today's success",
    'you are courage',
    'you believe in you',
    'you are sales',
    'youth is the product of invention',
    'yes is the best no',
    'yes is not a no',
    'yes is an idea',
    'yes is power',
    'yes is courage',
    'yes is not fear',
    'yes is never no',
    'yesterday is never today',
    'yes rhymes with business',
  ],

  z: [
    'zanny ideas are still ideas',
    'zuckerburg had an idea',
    'ziti is the pasta of success',
    'zero is the number of times you should fail',
    'zero is more than nothing',
    'zero is still a number',
    'zero is not a target',
    'zero courage is not dominance',
    'zero mistakes',
    'zero hate',
    'zero forfeiture',
    'zero tolerance',
    'zero windbreakers',
    'zero is an idea thats ready to be a one',
    'zero cannot be divided',
  ],
};
export default Phrases;
